language: bash
dist: xenial
services: docker

addons:
  apt:
    packages:
      - docker-ce
    update: true

env:
  - image=ad-decision
  - image=image/ffmpeg
  - image=account
  - image=ad-content/frontend
  - image=ad-content/archive
  - image=ad-insertion/frontend
  - image=ad-insertion/ad-static
  - image=ad-insertion/analytic-db
  - image=ad-insertion/ad-transcode
  - image=deployment
  - image=cdn
  - image=content-provider/transcode
  - image=content-provider/frontend
  - image=content-provider/archive

before_install:
  - docker version

script:
#  - mkdir build && cd build && cmake ..
#  - cd ${image}
#  - make 
  - echo Build ${image}

matrix:
  include:
  # ad-insertion/video-analytics-service
    - name: ad-insertion/video-analytics-service
      env: image=ad-insertion/video-analytics-service
      script: 
        - mkdir build && cd build && cmake ..
        - travis_wait 150 ${TRAVIS_BUILD_DIR}/script/travis_build.sh  ad-insertion/video-analytics-service
      after_failure:
        - tail --lines=5000 log_ad-insertion_video-analytics-service.log
